site_name:  HPCC
site_url:   https://example.com/
nav:
  - Systems:
    - Systems: '/systems'
    - Laputa: '/systems#laputa'
    - Naushikaa: '/systems#naushikaa'
    - Totoro: '/systems#totoro'
  - Inventory:
    - Inventory: '/inventory'
    - Servers: '/inventory#servers'
    - 'Raspberry Pis': '/inventory#raspberry-pis'
    - Networking: '/inventory#networking'
    - Other: '/inventory#other'
  - Guides: '/guides'
  - Powerpoints: '/powerpoints'
  - Resources: '/resources'
plugins:
  - search
theme:
  name: mkdocs
